Add draw yaw
etjump/etjump pull request #1390
Opened 2024-06-03 13:35 UTC by suburbski

Closes #873

2024-06-03 15:29 UTC, Aciz commented on src/cgame/etj_draw_yaw.cpp
> +  return true;
Why not `return (moveLeft || moveRight)` here?

2026-08-30 13:22 UTC, suburbski commented on src/cgame/etj_draw_yaw.cpp
> +  return true;
there's an early out now

2026-08-31 10:18 UTC, Aciz requested changes
I wonder if we also want something like `etj_yawWidth`, which would "push" the markers away from the drawing point, to the sides? that way you could for example clearly have the indicators on left and right side of your crosshair.

2026-08-31 10:18 UTC, Aciz commented on src/cgame/cg_local.h
> +extern vmCvar_t etj_drawYawSize;
This isn't the cvar naming convention we have, these should be
```
etj_drawYaw
etj_yawX
etj_yawY
etj_yawColor
etj_yawShadow
etj_yawSize
```

2026-08-31 10:21 UTC, Aciz commented
Also change base to `dev` pls

2026-09-02 08:54 UTC, Aciz approved these changes

2026-09-02 09:55 UTC, merged